using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Security;

public partial class Administracion_AnalistasPage : System.Web.UI.Page
{


    private ClaseAnalista Analistaok = new ClaseAnalista();
    private ClaseUsuario claseusuariook = new ClaseUsuario();

    protected void Page_Load(object sender, EventArgs e)
    {

        lb_nombre_cliente.Text = Convert.ToString( Session["nombreclienteoficina"]);

        lb_oficina.Text = " Oficina Codigo " + Session["codigooficina"] + " / Ciudad " + Session["ciudad"];


    }
    protected void tb_edicion_Click(object sender, EventArgs e)
    {

        if (this.GridView1.AutoGenerateEditButton)
        {
            tb_edicion.Text = "Habilitar Edición";
            this.GridView1.AutoGenerateEditButton = false;

        }
        else
        {
            tb_edicion.Text = "Deshabilitar Edición";
            this.GridView1.AutoGenerateEditButton = true;

        }


    }
    protected void tb_eliminacion_Click(object sender, EventArgs e)
    {
        if (this.GridView1.AutoGenerateDeleteButton)
        {
            tb_eliminacion.Text = "Habilitar Eliminacion";
            this.GridView1.AutoGenerateDeleteButton = false;


        }
        else
        {
            tb_eliminacion.Text = "Deshabilitar Eliminacion";
            this.GridView1.AutoGenerateDeleteButton = true;

        }
    }
    protected void tb_eliminacion0_Click(object sender, EventArgs e)
    {
        Panel1.Visible = true;
    }
    protected void tb_nuevo_Click(object sender, EventArgs e)
    {

               
         try
        {


             MembershipCreateStatus status;


            MembershipUser newUser = Membership.CreateUser(tb_correo.Text, "sincontra", tb_correo.Text, "pregunta", "respuesta", true, out status);



            if (newUser == null)
            {
                lb_info_operacion.Text = GetErrorMessage(status);
            }
            else
            {

                string usuariobuscar = tb_correo.Text;

                string traeridusuario = "ninguno";

                string mensajeu = "nopaso";


                claseusuariook.leeridusuario(usuariobuscar, ref traeridusuario, ref mensajeu);

                lb_info_operacion.Text = mensajeu;





                Analistaok.Nombres = tb_nombre.Text;

                Analistaok.Apellidos = tb_apellido.Text;

                Analistaok.Correo = tb_correo.Text;

                Analistaok.Telefono = tb_telefono.Text;

                Analistaok.Extencion = tb_extencion.Text;

                Analistaok.Celular = tb_celular.Text;

                Analistaok.Id_oficina = Convert.ToString(Session["codigooficina"]);

                Analistaok.Id_usuario = Convert.ToString(1);

                Analistaok.Id_usernuevo = traeridusuario;


                string infooper = "no esta pasando";

                Analistaok.nuevo(ref infooper);

                lb_info_operacion.Text = infooper;

                tb_nombre.Text = "";

                tb_apellido.Text = "";

                tb_correo.Text = "";

                tb_telefono.Text = "";

                tb_extencion.Text = "";

                tb_celular.Text = "";



                Panel1.Visible = false;

                Page.Response.Redirect("~/Administracion/AnalistasPage.aspx");


            }


        }
         
         catch
         {
             lb_info_operacion.Text = "An exception occurred creating the user.";
         }

        

    }


    public string GetErrorMessage(MembershipCreateStatus status)
    {
        switch (status)
        {
            case MembershipCreateStatus.DuplicateUserName:
                return "Username already exists. Please enter a different user name.";

            case MembershipCreateStatus.DuplicateEmail:
                return "A username for that e-mail address already exists. Please enter a different e-mail address.";

            case MembershipCreateStatus.InvalidPassword:
                return "The password provided is invalid. Please enter a valid password value.";

            case MembershipCreateStatus.InvalidEmail:
                return "The e-mail address provided is invalid. Please check the value and try again.";

            case MembershipCreateStatus.InvalidAnswer:
                return "The password retrieval answer provided is invalid. Please check the value and try again.";

            case MembershipCreateStatus.InvalidQuestion:
                return "The password retrieval question provided is invalid. Please check the value and try again.";

            case MembershipCreateStatus.InvalidUserName:
                return "The user name provided is invalid. Please check the value and try again.";

            case MembershipCreateStatus.ProviderError:
                return "The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator.";

            case MembershipCreateStatus.UserRejected:
                return "The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator.";

            default:
                return "An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator.";
        }
    }



    protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
    {


        GridViewRow row = GridView1.SelectedRow;

        Session["nombredeusuario"] = row.Cells[7].Text;


        Page.Response.Redirect("~/Usuarios/Analistas");


    }
}