using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;


public partial class ClientesPage : System.Web.UI.Page
{

    private ClaseCompania miobjeto = new ClaseCompania();



    protected void Page_Load(object sender, EventArgs e)
    {

    }
    protected void b_ver_todos_Click(object sender, EventArgs e)
    {

        Session["nombrecliente"] = "%";
        Panel1.Visible = false;


    }
    protected void b_ver_nuevo_Click(object sender, EventArgs e)
    {


         Panel1.Visible = true;

         Session["nombrecliente"] = "unvalordiferente";

    }
    protected void b_edicion_Click(object sender, EventArgs e)
    {

         if (GridView1.AutoGenerateEditButton) 

        {
            b_edicion.Text = "Habilitar Edición";
            GridView1.AutoGenerateEditButton = false;

            
        }

        else
       
         { 
        
             b_edicion.Text = "Deshabilitar Edición";
             GridView1.AutoGenerateEditButton = true;
        }
        

    }
    protected void b_eliminacion_Click(object sender, EventArgs e)
    {

         if (GridView1.AutoGenerateDeleteButton)

         {

            b_eliminacion.Text = "Habilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = false;

         }
        else

         {

             b_eliminacion.Text = "Deshabilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = true;

         }


    }
    protected void b_buscar_Click(object sender, EventArgs e)
    {


         if (tb_buscar.Text == "" )


            Label3.Text = "Ingrese Un Nombre";


        else

        {
            Session["nombrecliente"] = tb_buscar.Text;
        }

    }
    protected void b_nuevo_Click(object sender, EventArgs e)
    {
        
        

        string infooper = "no esta pasando";

       
        miobjeto.Nombre = tb_clientes.Text;

        miobjeto.nuevo(ref infooper);

        lb_info_operacion.Text = infooper;


        Session["nombrecliente"] = "%";


        tb_clientes.Text = "";
        
        Panel1.Visible = false;




                
    }

       


    protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
    {

        GridViewRow row = GridView1.SelectedRow;
        
        Session["idcliente"] = row.Cells[1].Text;
        Session["nombreclienteoficina"] = row.Cells[2].Text;

        Page.Response.Redirect("~/Administracion/OficinasPage.aspx");


    }
}