using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Administracion_DepartamentosPage : System.Web.UI.Page
{

    private ClaseCiudad ciudadesclass = new ClaseCiudad();

    protected void Page_Load(object sender, EventArgs e)
    {
        if (this.IsPostBack == false)
        {
            this.DropDownList1.DataSource = this.SqlDataSource2;
            this.DropDownList1.DataTextField = "Nombre";
            this.DropDownList1.DataValueField = "Id_departamento";
            this.DropDownList1.DataBind();

            DropDownList1.SelectedValue = Convert.ToString( Session["departamento"]);

        }
    }
    protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
    {
        Session["departamento"] = DropDownList1.SelectedValue;
    }
    protected void b_edicion_Click(object sender, EventArgs e)
    {
        if (this.GridView1.AutoGenerateEditButton)
        {
            b_edicion.Text = "Habilitar Edición";
            this.GridView1.AutoGenerateEditButton = false;

        }
        else
        {
            b_edicion.Text = "Deshabilitar Edición";
            this.GridView1.AutoGenerateEditButton = true;

        }
    }
    protected void b_eliminacion_Click(object sender, EventArgs e)
    {
        if (this.GridView1.AutoGenerateDeleteButton)
        {
            b_eliminacion.Text = "Habilitar Eliminacion";
            this.GridView1.AutoGenerateDeleteButton = false;


        }
        else
        {
            b_eliminacion.Text = "Deshabilitar Eliminacion";
            this.GridView1.AutoGenerateDeleteButton = true;

        }
    }
    protected void b_nuevaciudad_Click(object sender, EventArgs e)
    {
        Panel2.Visible = true;
    }
    protected void Button3_Click(object sender, EventArgs e)
    {
        ciudadesclass.Ciudad = tb_nuevo.Text;

        ciudadesclass.Departamento = DropDownList1.SelectedValue;

        string infooper = "no esta pasando";

        ciudadesclass.nuevo(ref infooper);

        lb_info_operacion.Text = infooper;

        Session["departamento"] = DropDownList1.SelectedValue;


        this.Response.Redirect("~/Administracion/DepartamentosPage.aspx");
    }
}