using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Security;

public partial class Administracion_InvestigadoresPage : System.Web.UI.Page
{

    private ClaseInvestigador Investigadoresok = new ClaseInvestigador();
    private ClaseUsuario claseusuariook = new ClaseUsuario();
    
    protected void Page_Load(object sender, EventArgs e)
    {

        if (this.IsPostBack == false)
        {
            this.DropDownList1.DataSource = this.SqlDataSource2;
            this.DropDownList1.DataTextField = "Nombre";
            this.DropDownList1.DataValueField = "Id_departamento";
            this.DropDownList1.DataBind();

            Session["departamento"] = "1";

            this.DropDownList2.DataSource = this.SqlDataSource3;
            this.DropDownList2.DataTextField = "Ciudad";
            this.DropDownList2.DataValueField = "Id_Ciudad";
            this.DropDownList2.DataBind();


        }
         

    }
    protected void tb_edicion_Click(object sender, EventArgs e)
    {

        if (this.GridView1.AutoGenerateEditButton)
        {
            tb_edicion.Text = "Habilitar Edición";
            this.GridView1.AutoGenerateEditButton = false;

        }
        else
        {
            tb_edicion.Text = "Deshabilitar Edición";
            this.GridView1.AutoGenerateEditButton = true;

        }


    }
    protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
    {
        Session["departamento"] = DropDownList1.SelectedValue;

        this.DropDownList2.DataSource = this.SqlDataSource3;
        this.DropDownList2.DataTextField = "Ciudad";
        this.DropDownList2.DataValueField = "Id_Ciudad";
        this.DropDownList2.DataBind();
    }
    protected void tb_eliminacion_Click(object sender, EventArgs e)
    {

        if (this.GridView1.AutoGenerateDeleteButton)
        {
            tb_eliminacion.Text = "Habilitar Eliminacion";
            this.GridView1.AutoGenerateDeleteButton = false;


        }
        else
        {
            tb_eliminacion.Text = "Deshabilitar Eliminacion";
            this.GridView1.AutoGenerateDeleteButton = true;

        }


    }
    protected void Button1_Click(object sender, EventArgs e)
    {
        Panel1.Visible = true;
    }
    protected void tb_nuevo_Click(object sender, EventArgs e)
    {


        try
        {

            MembershipCreateStatus status;


            MembershipUser newUser = Membership.CreateUser(tb_correo.Text, "sincontra", tb_correo.Text, "pregunta", "respuesta", true, out status);

            

            if (newUser == null)
            {
                lb_info_operacion.Text = GetErrorMessage(status);
            }
            else
            {

                string usuariobuscar = tb_correo.Text;

                string traeridusuario = "ninguno";

                string mensajeu = "nopaso";


                claseusuariook.leeridusuario(usuariobuscar, ref traeridusuario, ref mensajeu);

                lb_info_operacion.Text = mensajeu;


                Investigadoresok.Nombres = tb_nombre.Text;

                Investigadoresok.Apellidos = tb_apellido.Text;

                Investigadoresok.Cedula = tb_cedula.Text;

                Investigadoresok.Correo = tb_correo.Text;

                Investigadoresok.Telefono_fijo = tb_telefono.Text;

                Investigadoresok.Celular = tb_celular.Text;

                Investigadoresok.Barrio = tb_barrio.Text;

                Investigadoresok.Direccion = tb_direccion.Text;

                Investigadoresok.Ubicacion = this.DropDownList2.SelectedValue;

                Investigadoresok.Id_usuario = Convert.ToString(1);

                Investigadoresok.Id_usernuevo = traeridusuario;

                string infooper = "no esta pasando";

                Investigadoresok.nuevo(ref infooper);

                lb_info_operacion.Text = infooper;

                tb_nombre.Text = "";

                tb_apellido.Text = "";

                tb_cedula.Text = "";

                tb_correo.Text = "";

                tb_telefono.Text = "";

                tb_celular.Text = "";

                tb_barrio.Text = "";


                Panel1.Visible = false;

                Page.Response.Redirect("~/Administracion/InvestigadoresPage.aspx");
                                      
                        
            }

                               
                      


        }
        catch
        {
            lb_info_operacion.Text = "An exception occurred creating the user.";
        }



                            
                
        
       

    }


    public string GetErrorMessage(MembershipCreateStatus status)
    {
        switch (status)
        {
            case MembershipCreateStatus.DuplicateUserName:
                return "Username already exists. Please enter a different user name.";

            case MembershipCreateStatus.DuplicateEmail:
                return "A username for that e-mail address already exists. Please enter a different e-mail address.";

            case MembershipCreateStatus.InvalidPassword:
                return "The password provided is invalid. Please enter a valid password value.";

            case MembershipCreateStatus.InvalidEmail:
                return "The e-mail address provided is invalid. Please check the value and try again.";

            case MembershipCreateStatus.InvalidAnswer:
                return "The password retrieval answer provided is invalid. Please check the value and try again.";

            case MembershipCreateStatus.InvalidQuestion:
                return "The password retrieval question provided is invalid. Please check the value and try again.";

            case MembershipCreateStatus.InvalidUserName:
                return "The user name provided is invalid. Please check the value and try again.";

            case MembershipCreateStatus.ProviderError:
                return "The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator.";

            case MembershipCreateStatus.UserRejected:
                return "The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator.";

            default:
                return "An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator.";
        }
    }


    protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
    {

        GridViewRow row = GridView1.SelectedRow;

        Session["nombredeusuario"] = row.Cells[7].Text;
        
        Page.Response.Redirect("~/Usuarios/Investigadores");


    }

    protected void DropDownList2_SelectedIndexChanged(object sender, EventArgs e)
    {

    }
}