using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Administracion_OficinasPage : System.Web.UI.Page
{


    private ClaseOficina Oficinaok = new ClaseOficina();

    protected void Page_Load(object sender, EventArgs e)
    {

        if (this.IsPostBack == false)
        {
            this.DropDownList1.DataSource = this.SqlDataSource2;
            this.DropDownList1.DataTextField = "Nombre";
            this.DropDownList1.DataValueField = "Id_departamento";
            this.DropDownList1.DataBind();

            Session["departamento"] = "1";

            this.DropDownList2.DataSource = this.SqlDataSource3;
            this.DropDownList2.DataTextField = "Ciudad";
            this.DropDownList2.DataValueField = "Id_Ciudad";
            this.DropDownList2.DataBind();


        }


        lb_nombre_cliente.Text = Convert.ToString( Session["nombreclienteoficina"]);




    }
    protected void tb_edicion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateEditButton)
        {
            tb_edicion.Text = "Habilitar Edición";
            GridView1.AutoGenerateEditButton = false;


        }

        else
        {

            tb_edicion.Text = "Deshabilitar Edición";
            GridView1.AutoGenerateEditButton = true;
        }
        
    }
    protected void tb_eliminacion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateDeleteButton)
        {

            tb_eliminacion.Text = "Habilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = false;

        }
        else
        {

            tb_eliminacion.Text = "Deshabilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = true;

        }

    }
    protected void Button1_Click(object sender, EventArgs e)
    {
        Panel1.Visible = true;
    }
    protected void tb_nuevo_Click(object sender, EventArgs e)
    {

        Oficinaok.Direccion = tb_Direccion0.Text;

        Oficinaok.Telefono = tb_telefono.Text;

        Oficinaok.Id_compania = Convert.ToString(Session["idcliente"]);

        Oficinaok.Ubicacion = this.DropDownList2.SelectedValue;



        string infooper = "no esta pasando";

        Oficinaok.nuevo(ref infooper);

        lb_info_operacion.Text = infooper;

        tb_Direccion0.Text = "";
        tb_telefono.Text = "";


        Panel1.Visible = false;

        Page.Response.Redirect("~/Administracion/OficinasPage.aspx");


    }
    protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
    {

        GridViewRow row = GridView1.SelectedRow;

        Session["codigooficina"] = row.Cells[1].Text;
        Session["ciudad"] = row.Cells[5].Text;

        Page.Response.Redirect("~/Administracion/AnalistasPage.aspx");


    }
    protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
    {
        Session["departamento"] = DropDownList1.SelectedValue;

        this.DropDownList2.DataSource = this.SqlDataSource3;
        this.DropDownList2.DataTextField = "Ciudad";
        this.DropDownList2.DataValueField = "Id_Ciudad";
        this.DropDownList2.DataBind();


    }
}