using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Contenidos_InfoReclamantesPage : System.Web.UI.Page
{

    private ClaseReclamantes reclamantesok = new ClaseReclamantes();
    private ClaseAfiliado afiliadook = new ClaseAfiliado();


    protected void Page_Load(object sender, EventArgs e)
    {

        HyperLink1.NavigateUrl = "~/VisualizadorDeCasos.aspx" + Convert.ToString(Session["NumeroDeCaso"]) + "punto" + "AnclaReclamantes" + "#AnclaReclamantes";

        if (this.IsPostBack == false)
        {
            this.DropDownList1.DataSource = this.SqlDataSource2;
            this.DropDownList1.DataTextField = "Nombre";
            this.DropDownList1.DataValueField = "Id_departamento";
            this.DropDownList1.DataBind();

            Session["departamento"] = "1";

            this.DropDownList2.DataSource = this.SqlDataSource3;
            this.DropDownList2.DataTextField = "Ciudad";
            this.DropDownList2.DataValueField = "Id_Ciudad";
            this.DropDownList2.DataBind();


        }


    }
    protected void Button2_Click(object sender, EventArgs e)
    {
        



        string varito = "no paso";
        string IdAfiliado = "nada";
        string varito2 = "no paso";

        afiliadook.leeridafiliado(Convert.ToString(Session["NumeroDeCaso"]), ref IdAfiliado, ref varito2);

        lb_info_operacion2.Text = varito2;


        reclamantesok.Id_afiliado = IdAfiliado;

        reclamantesok.Id_laborales = "";

        reclamantesok.Id_Numero_Caso = Convert.ToString(Session["NumeroDeCaso"]);
        
        reclamantesok.Apellido = tb_apellido.Text;

        reclamantesok.Barrio = tb_barrio.Text;
        
        reclamantesok.Cedula = tb_cedula.Text;

        reclamantesok.Celular = tb_celular.Text;

        reclamantesok.Ciudad = DropDownList2.SelectedValue;
        
        reclamantesok.Direccion = tb_direccion.Text;

        reclamantesok.Nombre = tb_nombre.Text;

        reclamantesok.Parentesco = tb_parentesco.Text;

        reclamantesok.Telefono = tb_telefono.Text;
        
        reclamantesok.nuevo(ref varito);
        
        lb_info_operacion.Text = varito;


        Response.Redirect("~/Contenidos/InfoReclamantesPage.aspx");


    }
    protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
    {
        Session["departamento"] = DropDownList1.SelectedValue;

        this.DropDownList2.DataSource = this.SqlDataSource3;
        this.DropDownList2.DataTextField = "Ciudad";
        this.DropDownList2.DataValueField = "Id_Ciudad";
        this.DropDownList2.DataBind();
    }
    protected void b_edicion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateEditButton)
        {
            b_edicion.Text = "Habilitar Edición";
            GridView1.AutoGenerateEditButton = false;


        }

        else
        {

            b_edicion.Text = "Deshabilitar Edición";
            GridView1.AutoGenerateEditButton = true;
        }
    }
    protected void b_eliminacion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateDeleteButton)
        {

            b_eliminacion.Text = "Habilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = false;

        }
        else
        {

            b_eliminacion.Text = "Deshabilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = true;

        }
    }
    protected void Button1_Click(object sender, EventArgs e)
    {
        Panel1.Visible = true;
    }
    protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
    {
        GridViewRow row = GridView1.SelectedRow;

        Session["identifireclamantes"] = row.Cells[1].Text;

        Page.Response.Redirect("~/infolaboral/reclamantes");
    }
}