using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Security;
using System.Web.Configuration;

public partial class Contenidos_InfoAfiliadoPage : System.Web.UI.Page
{

    private ClaseAfiliado afiliadook = new ClaseAfiliado();

    protected void Page_Load(object sender, EventArgs e)
    {

        HyperLink1.NavigateUrl = "~/VisualizadorDeCasos.aspx" + Convert.ToString(Session["NumeroDeCaso"]) + "punto" + "AnclaDafiliado" + "#AnclaDafiliado";

        string casonuevo = Convert.ToString(Session["casonuevo"]);

        if (casonuevo == "true")
        {

            Panel1.Visible = true;

            Session["casonuevo"] = "";

        }
        
        
        if (this.IsPostBack == false)
        {
            this.DropDownList1.DataSource = this.SqlDataSource2;
            this.DropDownList1.DataTextField = "Nombre";
            this.DropDownList1.DataValueField = "Id_departamento";
            this.DropDownList1.DataBind();

            Session["departamento"] = "1";

            this.DropDownList2.DataSource = this.SqlDataSource3;
            this.DropDownList2.DataTextField = "Ciudad";
            this.DropDownList2.DataValueField = "Id_Ciudad";
            this.DropDownList2.DataBind();


        }
    }
    protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
    {
        Session["departamento"] = DropDownList1.SelectedValue;

        this.DropDownList2.DataSource = this.SqlDataSource3;
        this.DropDownList2.DataTextField = "Ciudad";
        this.DropDownList2.DataValueField = "Id_Ciudad";
        this.DropDownList2.DataBind();
    }
    protected void Button1_Click(object sender, EventArgs e)
    {
       
    }
    protected void Button2_Click(object sender, EventArgs e)
    {

        string varito = "no paso";
        
        afiliadook.Id_Numero_Caso = Convert.ToString(Session["NumeroDeCaso"]);
            
        afiliadook.Id_laborales = "";
        
        afiliadook.Nombre = tb_nombre.Text;

        afiliadook.Apellido = tb_apellido.Text;

        afiliadook.Cedula = tb_cedula.Text;

        afiliadook.Ciudad = DropDownList2.SelectedValue;

        afiliadook.Direccion = tb_direccion.Text;

        afiliadook.Barrio = tb_barrio.Text;

        afiliadook.Celular = tb_celular.Text;

        afiliadook.Telefono = tb_telefono.Text;

        afiliadook.nuevo(ref varito);

        lb_info_operacion.Text = varito;



        // Envia correo electronico a analista con confirmacion de nuevo caso


        System.Net.Mail.MailMessage mensaje4 = new System.Net.Mail.MailMessage();


        mensaje4.To.Add(DropDownList3.SelectedValue);


        mensaje4.Subject = "Caso Asignado Con Exito # " + Convert.ToString(Session["NumeroDeCaso"]) + " Afiliado: " + tb_nombre.Text + " " + tb_apellido.Text + "#---" + DateTime.Now;

        mensaje4.IsBodyHtml = true;



        mensaje4.Body = "<h3> Caso Asignado Con Exito a Consultando Ltda <br /><br /> Numero De Asignacion: " + Convert.ToString(Session["NumeroDeCaso"]) + "<br /><br /> <h3> Afiliado: " + tb_nombre.Text + " " + tb_apellido.Text + "</h3> <br /> <h3> Cedula: " + tb_cedula.Text + " </h3> <br /> <br />" + "<h1> <a href='" + WebConfigurationManager.AppSettings["RutaPagina"] + "/VisualizadorDeCasos.aspx" + Convert.ToString(Session["NumeroDeCaso"]) + "puntonormal#normal'> Ver Nuevo Caso Asignado </a> </h1>";




        dynamic smpt2 = new System.Net.Mail.SmtpClient();


        try
        {
            smpt2.Send(mensaje4);
        }

        catch (Exception err)
        {
            lb_info_operacion.Text = Convert.ToString(err);

        }




        Page.Response.Redirect("~/VisualizadorDeCasos.aspx" + Convert.ToString(Session["NumeroDeCaso"]) + "punto" + "normal");

    }
    protected void b_edicion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateEditButton)
        {
            b_edicion.Text = "Habilitar Edición";
            GridView1.AutoGenerateEditButton = false;


        }

        else
        {

            b_edicion.Text = "Deshabilitar Edición";
            GridView1.AutoGenerateEditButton = true;
        }
    }
    protected void b_eliminacion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateDeleteButton)
        {

            b_eliminacion.Text = "Habilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = false;

        }
        else
        {

            b_eliminacion.Text = "Deshabilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = true;

        }
    }
    protected void GridView1_SelectedIndexChanged(object sender, EventArgs e)
    {

        GridViewRow row = GridView1.SelectedRow;

        Session["identifiafiliado"] = row.Cells[1].Text;

        Page.Response.Redirect("~/infolaboral/afiliado");

    }
}