using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Contenidos_InfoLaboralPage : System.Web.UI.Page
{

    private ClaseLaborales laboralesok = new ClaseLaborales();
    private ClaseAfiliado afiliadook = new ClaseAfiliado();
    private ClaseReclamantes reclamantesok = new ClaseReclamantes();

    string infoID;


    protected void Page_Load(object sender, EventArgs e)
    {

        
       
        
        infoID = (string)Page.RouteData.Values["infoID"];

        if (infoID == "afiliado")
            
        {

            HyperLink1.NavigateUrl = "~/VisualizadorDeCasos.aspx" + Convert.ToString(Session["NumeroDeCaso"]) + "punto" + "AnclaDafiliado" + "#AnclaDafiliado";
            
            GridView1.DataSourceID = "SqlDataSource1";

            lb_tipolaborales.Text = "Afiliado";


            lb_info_operacion2.Text = "Afiliado";
        
        
        }
                

        if (infoID == "reclamantes")
        {

            HyperLink1.NavigateUrl = "~/VisualizadorDeCasos.aspx" + Convert.ToString(Session["NumeroDeCaso"]) + "punto" + "AnclaReclamantes" + "#AnclaReclamantes";
            
            GridView1.DataSourceID = "SqlDataSource4";

            lb_tipolaborales.Text = "Reclamantes";


            lb_info_operacion2.Text = "Reclamantes";
        
        }

       

        if (this.IsPostBack == false)
        {
            this.DropDownList1.DataSource = this.SqlDataSource2;
            this.DropDownList1.DataTextField = "Nombre";
            this.DropDownList1.DataValueField = "Id_departamento";
            this.DropDownList1.DataBind();

            Session["departamento"] = "1";

            this.DropDownList2.DataSource = this.SqlDataSource3;
            this.DropDownList2.DataTextField = "Ciudad";
            this.DropDownList2.DataValueField = "Id_Ciudad";
            this.DropDownList2.DataBind();


        }
    }
    protected void b_edicion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateEditButton)
        {
            b_edicion.Text = "Habilitar Edición";
            GridView1.AutoGenerateEditButton = false;


        }

        else
        {

            b_edicion.Text = "Deshabilitar Edición";
            GridView1.AutoGenerateEditButton = true;
        }
    }
    protected void b_eliminacion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateDeleteButton)
        {

            b_eliminacion.Text = "Habilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = false;

        }
        else
        {

            b_eliminacion.Text = "Deshabilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = true;

        }
    }
    protected void Button1_Click(object sender, EventArgs e)
    {
        Panel1.Visible = true;
    }
    protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
    {
        Session["departamento"] = DropDownList1.SelectedValue;

        this.DropDownList2.DataSource = this.SqlDataSource3;
        this.DropDownList2.DataTextField = "Ciudad";
        this.DropDownList2.DataValueField = "Id_Ciudad";
        this.DropDownList2.DataBind();
    }
    
    protected void Button2_Click(object sender, EventArgs e)
    {

        if (infoID == "afiliado") {



            
            //string IdAfiliado = "nada";
            //string varito2 = "no paso";

            //afiliadook.leeridafiliado(Convert.ToString(Session["NumeroDeCaso"]), ref IdAfiliado, ref varito2);


            //lb_info_operacion2.Text = varito2;


            laboralesok.Id_afiliado = Convert.ToString(Session["identifiafiliado"]);

            laboralesok.Id_reclamantes = "";

                    
        }


        if (infoID == "reclamantes")
        {

            //string Idreclamante = "nada";
            //string varito2 = "no paso";


            //reclamantesok.leeridreclamante(Convert.ToString(Session["NumeroDeCaso"]), ref Idreclamante, ref varito2);

            //lb_info_operacion2.Text = varito2;


            laboralesok.Id_afiliado = "";

            laboralesok.Id_reclamantes = Convert.ToString(Session["identifireclamantes"]);


        }




        string varito = "no paso";

        laboralesok.Barrio = tb_barrio.Text;
        laboralesok.Cargo = tb_cargo.Text;
        laboralesok.Celular = tb_celular.Text;
        laboralesok.Ciudad = DropDownList2.SelectedValue;
        laboralesok.Direccion = tb_direccion.Text;
        laboralesok.Email_contacto = tb_emailcontacto.Text;
        laboralesok.Email_empresa = tb_mailempresa.Text;
        laboralesok.Extencion = tb_extencion.Text;
        laboralesok.Fax = tb_fax.Text;
        laboralesok.Nombre_empresa = tb_empresa.Text;
        laboralesok.Persona_Contacto = tb_personaconta.Text;
        laboralesok.Telefono = tb_telefono.Text;
        
               
        laboralesok.nuevo(ref varito);
        
        lb_info_operacion.Text = varito;




        tb_barrio.Text = "";
        tb_cargo.Text = "";
        tb_celular.Text = "";
        tb_direccion.Text = "";
        tb_emailcontacto.Text = "";
        tb_mailempresa.Text = "";
        tb_extencion.Text = "";
        tb_fax.Text = "";
        tb_empresa.Text = "";
        tb_personaconta.Text = "";
        tb_telefono.Text = "";
        
        
        
        Panel1.Visible = false;

    }
    
    protected void DropDownList2_SelectedIndexChanged(object sender, EventArgs e)
    {

    }
}