using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Web.Security;
using System.Web.Configuration;

public partial class Contenidos_ResumenesPage : System.Web.UI.Page
{

    private ClaseResumenes resumenok = new ClaseResumenes();


    string nuevoresID;

    protected void Page_Load(object sender, EventArgs e)
    {

        HyperLink1.NavigateUrl = "~/VisualizadorDeCasos.aspx" + Convert.ToString(Session["NumeroDeCaso"]) + "punto" + "AnclaResumenes" + "#AnclaResumenes";


        if (this.IsPostBack == false)
        {


            /////
            string diadato;
            int dia;

            dia = DateTime.Now.Day;


            if (dia < 10)
            {

                diadato =  Convert.ToString(dia);


            }
            else
            {


                diadato = Convert.ToString(dia);

            }


            string mesdato;
            int mes;

            mes = DateTime.Now.Month;


            if (mes < 10)
            {

                mesdato =  Convert.ToString(mes);


            }
            else
            {


                mesdato = Convert.ToString(mes);

            }

            string dato;




            dato = mesdato + "/" + diadato + "/" + Convert.ToString(DateTime.Now.Year);

            Session["fechabitacoras"] = dato;

            lb_fechadeasignacion.Text = dato;

            //////////////

        }

        nuevoresID = (string)Page.RouteData.Values["nuevoresID"];


        if (nuevoresID == "Casos")
        {

            Calendar1.Visible = false;
            Button3.Visible = false;
            DropDownList1.Visible = false;
            lb_fechadeasignacion.Visible = false;
            Label6.Visible = false;
            Label5.Visible = false;



            Label3.Text = "Nuevos Apuntes";


            GridView1.Columns[10].Visible = false;

            GridView1.Columns[11].Visible = false;

            GridView1.Columns[12].Visible = false;
            
            Button1.Visible = true;

        }


        if (nuevoresID == "Revisar")
        {

            Label3.Text = "Bitacora De Casos";

            GridView1.DataSourceID = "SqlDataSource2";

            Session["investigadorresumenes"] = "%";
            
            Session["estadoresumen567"] = "%";

            GridView1.Columns[10].Visible = false;

            GridView1.Columns[11].Visible = false;

        }

        if (nuevoresID == "Bitacora De Casos")
        {

            Label3.Text = "Corregir Resumenes";

            GridView1.DataSourceID = "SqlDataSource2";

            Session["investigadorresumenes"] = Convert.ToString(Membership.GetUser());


            if (Roles.IsUserInRole("AreaOperativa"))
            {

                Session["investigadorresumenes"] = "%";

            }


            Session["estadoresumen567"] = "%";

            GridView1.Columns[10].Visible = false;

            GridView1.Columns[11].Visible = false;
           
            GridView1.Columns[12].Visible = false;

        }


        if (nuevoresID == "Publicado")
        {

            Label3.Text = "Resumenes Publicados";

            GridView1.DataSourceID = "SqlDataSource2";

            Session["investigadorresumenes"] = "%";

            Session["estadoresumen567"] = "Publicado";

            //GridView1.Columns[12].Visible = false;

        }

        
        
        
      
                        
    }


    protected void Button1_Click(object sender, EventArgs e)
    {
        Panel1.Visible = true;
        Button2.Visible = true;

    }
    protected void b_edicion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateEditButton)
        {
            b_edicion.Text = "Habilitar Edición";
            GridView1.AutoGenerateEditButton = false;


        }

        else
        {

            b_edicion.Text = "Deshabilitar Edición";
            GridView1.AutoGenerateEditButton = true;
        }
    }
    protected void b_eliminacion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateDeleteButton)
        {

            b_eliminacion.Text = "Habilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = false;

        }
        else
        {

            b_eliminacion.Text = "Deshabilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = true;

        }
    }
    protected void Button2_Click(object sender, EventArgs e)
    {

        string varito = "no paso";



        resumenok.Id_numero_de_Caso = Convert.ToString(Session["NumeroDeCaso"]);

        resumenok.Fecha = Convert.ToString(DateTime.Now);

        resumenok.Informe = tb_resumen.Text;

        resumenok.Id_estadodocus = "1";
        

        resumenok.nuevo(ref varito);

        lb_info_operacion.Text = varito;



        if (nuevoresID == "Casos")
        {

            Page.Response.Redirect("~/Resumenes/Casos");

        }


        if (nuevoresID == "Revisar")
        {

            Page.Response.Redirect("~/Resumenes/Revisar");

        }

        if (nuevoresID == "Corregir")
        {

            Page.Response.Redirect("~/Resumenes/Corregir");

        }


        if (nuevoresID == "Publicado")
        {

            Page.Response.Redirect("~/Resumenes/Publicado");

        }


       
        
    }



    protected void GridView1_RowCommand(object sender, GridViewCommandEventArgs e)
    {
       

        
        if (e.CommandName == "ActualizarAnexo")
        {

            int index = Convert.ToInt32(e.CommandArgument);

            GridViewRow row = GridView1.Rows[index];

            string mensaje = "nada";

            Session["codigoresumen"] = row.Cells[1].Text;

            resumenok.traercaso(row.Cells[1].Text, ref mensaje);

            Label2.Text = mensaje;

            Panel1.Visible = true;

            Button10.Visible = true;
            
            tb_resumen.Text = resumenok.Informe;


        }


        if (e.CommandName == "Corregirw")
        {

            int index = Convert.ToInt32(e.CommandArgument);

            GridViewRow row = GridView1.Rows[index];


            string mensaje = "nada";

            resumenok.Id_estadodocus = "2";

            resumenok.actualizarestado(row.Cells[1].Text, ref mensaje);

            Label2.Text = mensaje;



            System.Net.Mail.MailMessage mensaje3 = new System.Net.Mail.MailMessage();


            mensaje3.To.Add(row.Cells[9].Text);


            mensaje3.Subject = "Por favor Corregir Resumen  " + row.Cells[2].Text + " Afiliado: " + row.Cells[7].Text + " " + row.Cells[8].Text +""+ DateTime.Now;

            mensaje3.IsBodyHtml = true;



            mensaje3.Body = "<img src='http://consultandoweb.com/consulcaso/logo.png' alt='ConsulCaso7'> <br />" + "<h2> Por favor Corregir Resumen:</h2> <h3><i> " + row.Cells[2].Text + "</i></h3> <br />" + "<h2> Afiliado: </h2><br /><h3><i>" + row.Cells[7].Text + " " + row.Cells[8].Text + "</i></h3> <br />" + " <br /> <h2> Resumen: </h2><br /><h3><i>" + row.Cells[4].Text + "</i> </h3> <br />" + " <br />" + " <h2> Puede Ver Todos Los Resumenes Por Corregir Dando Clic En El Siguiente Enlace </h2>" + " <br />" + "<h1> <a href='" + WebConfigurationManager.AppSettings["RutaPagina"] + "/Resumenes/Corregir'> Ver Todos Los Resumenes Por Corregir </a> </h1>";

            dynamic smpt = new System.Net.Mail.SmtpClient();


            
             try
                     {


            smpt.Send(mensaje3);

                     }
             catch (Exception err)
             {
                 lb_info_operacion.Text = Convert.ToString(err);

             }


            if (nuevoresID == "Casos")
            {

                Page.Response.Redirect("~/Resumenes/Casos");

            }


            if (nuevoresID == "Revisar")
            {

                Page.Response.Redirect("~/Resumenes/Revisar");

            }

            if (nuevoresID == "Corregir")
            {

                Page.Response.Redirect("~/Resumenes/Corregir");

            }


            if (nuevoresID == "Publicado")
            {

                Page.Response.Redirect("~/Resumenes/Publicado");

            }

        }

        if (e.CommandName == "revisar23")
        {

            int index = Convert.ToInt32(e.CommandArgument);

            GridViewRow row = GridView1.Rows[index];


            string mensaje = "nada";

            resumenok.Id_estadodocus = "1";

            resumenok.actualizarestado(row.Cells[1].Text, ref mensaje);

            Label2.Text = mensaje;

            if (nuevoresID == "Casos")
            {

                Page.Response.Redirect("~/Resumenes/Casos");

            }


            if (nuevoresID == "Revisar")
            {

                Page.Response.Redirect("~/Resumenes/Revisar");

            }

            if (nuevoresID == "Corregir")
            {

                Page.Response.Redirect("~/Resumenes/Corregir");

            }


            if (nuevoresID == "Publicado")
            {

                Page.Response.Redirect("~/Resumenes/Publicado");

            }

        }


        if (e.CommandName == "Publicarq")
        {
          
            int index = Convert.ToInt32(e.CommandArgument);

            GridViewRow row = GridView1.Rows[index];


            string mensaje = "nada";

            resumenok.Id_estadodocus = "4";

            resumenok.actualizarestado(row.Cells[1].Text, ref mensaje);

            Label2.Text = mensaje;


            // mensaje enviado a analaista

            
            System.Net.Mail.MailMessage mensaje3 = new System.Net.Mail.MailMessage();


            mensaje3.To.Add(row.Cells[6].Text);


            mensaje3.Subject = "Nuevo Apunte En La Bitacora Del Caso: " + row.Cells[2].Text + " Afiliado: " + row.Cells[7].Text + " " + row.Cells[8].Text + " " + DateTime.Now;

            
            
            
            
            mensaje3.IsBodyHtml = true;



            mensaje3.Body = "<img src='http://consultandoweb.com/consulcaso/logo.png' alt='ConsulCaso7'> <br />" + "<h2> Nuevo Apunte En La Bitacora Del Caso:</h2> <h3><i> " + row.Cells[2].Text + "</i></h3> <br />" + "<h2> Afiliado: </h2><br /><h3><i>" + row.Cells[7].Text + " " + row.Cells[8].Text + "</i></h3> <br />" + " <br /> <h2> Apunte: </h2><br /><h3><i>" + row.Cells[4].Text + " </i> </h3> <br />" + " <br />" + " <h2> Puede Ver La Bitacora Del Caso Con Todos Sus Apuntes Dando Clic En El Siguiente Enlace </h2>" + " <br />" + "<h1> <a href='" + WebConfigurationManager.AppSettings["RutaPagina"] + "/VisualizadorDeCasos.aspx" + row.Cells[2].Text + "puntoAnclaResumenes#AnclaResumenes'> Ver Bitacora Del Caso </a> </h1>";

            
            
            
            dynamic smpt = new System.Net.Mail.SmtpClient();


             try
                     {

            smpt.Send(mensaje3);

                     }
             catch (Exception err)
             {
                 lb_info_operacion.Text = Convert.ToString(err);

             }


            if (nuevoresID == "Casos")
            {

                Page.Response.Redirect("~/Resumenes/Casos");

            }


            if (nuevoresID == "Revisar")
            {

                Page.Response.Redirect("~/Resumenes/Revisar");

            }

            if (nuevoresID == "Corregir")
            {

                Page.Response.Redirect("~/Resumenes/Corregir");

            }


            if (nuevoresID == "Publicado")
            {

                Page.Response.Redirect("~/Resumenes/Publicado");

            }

        }


    }


    protected void Button7_Click(object sender, EventArgs e)
    {

      

       
    }
    protected void Button6_Click(object sender, EventArgs e)
    {
      
    }
    
  

    protected void Button10_Click(object sender, EventArgs e)
    {
       string mensaje = "nada";

        resumenok.Informe = tb_resumen.Text;

        resumenok.actualizarinforme(Convert.ToString(Session["codigoresumen"]), ref mensaje);

        Label2.Text = mensaje;

        if (nuevoresID == "Casos")
        {

            Page.Response.Redirect("~/Resumenes/Casos");

           
        }


        if (nuevoresID == "Revisar")
        {

            Page.Response.Redirect("~/Resumenes/Revisar");
            Session["fechabitacoras"] = "%";
        }

        if (nuevoresID == "Corregir")
        {

            Page.Response.Redirect("~/Resumenes/Corregir");
            Session["fechabitacoras"] = "%";
        }


        if (nuevoresID == "Publicado")
        {

            Page.Response.Redirect("~/Resumenes/Publicado");

        }
    }
    protected void Calendar1_SelectionChanged(object sender, EventArgs e)
    {

        string diadato;
        int dia;

        dia = Calendar1.SelectedDate.Day;


        if (dia < 10)
        {

            diadato =  Convert.ToString(dia);


        }
        else 
        {


            diadato =  Convert.ToString(dia);
        
        }


        string mesdato;
        int mes;

        mes = Calendar1.SelectedDate.Month;


        if (mes < 10)
        {

            mesdato =  Convert.ToString(mes);


        }
        else
        {


            mesdato = Convert.ToString(mes);

        }

        string dato;



        dato = mesdato + "/" + diadato + "/" + Convert.ToString(Calendar1.SelectedDate.Year);

        Session["fechabitacoras"] = dato;

        lb_fechadeasignacion.Text = dato;
    }
    protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
    {
        Session["fechabitacoras"] = DropDownList1.SelectedValue + Convert.ToString(DateTime.Now.Year);
        
        lb_fechadeasignacion.Text = DropDownList1.SelectedValue + Convert.ToString(DateTime.Now.Year);
    }
    protected void Button3_Click(object sender, EventArgs e)
    {
        Session["fechabitacoras"] = "%";
    }
}