using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Contenidos_SeguimientosPage : System.Web.UI.Page
{

    private ClaseSeguimientos seguimientosok = new ClaseSeguimientos();
    private ClaseAfiliado afiliadook = new ClaseAfiliado();

    protected void Page_Load(object sender, EventArgs e)
    {


        HyperLink1.NavigateUrl = "~/VisualizadorDeCasos.aspx" + Convert.ToString(Session["NumeroDeCaso"]) + "punto" + "AnclaSeguimiento" + "#AnclaSeguimiento";

        if (this.IsPostBack == false)
        {
            this.DropDownList1.DataSource = this.SqlDataSource2;
            this.DropDownList1.DataTextField = "Nombre";
            this.DropDownList1.DataValueField = "Id_departamento";
            this.DropDownList1.DataBind();

            Session["departamento"] = "1";

            this.DropDownList2.DataSource = this.SqlDataSource3;
            this.DropDownList2.DataTextField = "Ciudad";
            this.DropDownList2.DataValueField = "Id_Ciudad";
            this.DropDownList2.DataBind();


        }


    }
    protected void DropDownList1_SelectedIndexChanged(object sender, EventArgs e)
    {
        Session["departamento"] = DropDownList1.SelectedValue;

        this.DropDownList2.DataSource = this.SqlDataSource3;
        this.DropDownList2.DataTextField = "Ciudad";
        this.DropDownList2.DataValueField = "Id_Ciudad";
        this.DropDownList2.DataBind();
    }
    protected void Calendar1_SelectionChanged(object sender, EventArgs e)
    {
        lb_fecha.Text = Convert.ToString(Calendar1.SelectedDate.Day);

        lb_fecha.Text = lb_fecha.Text + "/" + Convert.ToString(Calendar1.SelectedDate.Month);

        lb_fecha.Text = lb_fecha.Text + "/" + Convert.ToString(Calendar1.SelectedDate.Year);
    }
    protected void Button2_Click(object sender, EventArgs e)
    {
        string varito = "no paso";
        string IdAfiliado = "nada";
        string varito2 = "no paso";

        afiliadook.leeridafiliado(Convert.ToString(Session["NumeroDeCaso"]), ref IdAfiliado, ref varito2);

        
        lb_info_operacion2.Text = varito2;


        seguimientosok.Id_afiliado = IdAfiliado;

        seguimientosok.Celular = tb_celular.Text;

        seguimientosok.Ciudad = DropDownList2.SelectedValue; 

        seguimientosok.Direccion = tb_direccio.Text;

        seguimientosok.Entidad = tb_entidad.Text;

        seguimientosok.Extencion = tb_extencion.Text;

        seguimientosok.Fecha = lb_fecha.Text;

        seguimientosok.Hora = tb_hora.Text;

        seguimientosok.Nombre_contacto = tb_nombre.Text;

        seguimientosok.Telefono = tb_telefono.Text;
        
        seguimientosok.nuevo(ref varito);

        lb_info_operacion.Text = varito;


        Response.Redirect("~/Contenidos/SeguimientosPage.aspx");

    }
    protected void Button1_Click(object sender, EventArgs e)
    {
        Panel1.Visible = true;
    }
    protected void b_edicion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateEditButton)
        {
            b_edicion.Text = "Habilitar Edición";
            GridView1.AutoGenerateEditButton = false;


        }

        else
        {

            b_edicion.Text = "Deshabilitar Edición";
            GridView1.AutoGenerateEditButton = true;
        }
    }
    protected void b_eliminacion_Click(object sender, EventArgs e)
    {
        if (GridView1.AutoGenerateDeleteButton)
        {

            b_eliminacion.Text = "Habilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = false;

        }
        else
        {

            b_eliminacion.Text = "Deshabilitar Eliminacion";
            GridView1.AutoGenerateDeleteButton = true;

        }    
    }
}